# Claude Agent Hub 配置文件

# 后端配置（可选: claude-code / opencode / iflow）
# backend:
#   type: opencode
#   model: opencode/trinity-large-preview-free

# Agent 配置
agents:
  - name: dev
    persona: Pragmatist
    schedule:
      poll_interval: 5m # 任务轮询间隔

  # 可以添加更多 Agent
  # - name: reviewer
  #   persona: Perfectionist
  #   role: reviewer

# 任务配置
tasks:
  default_priority: medium
  max_retries: 3
  timeout: 30m

# Git 配置
git:
  base_branch: main
  branch_prefix: 'agent/'
  auto_push: false # 需要人工确认才推送

